/**
 * Validates an icon URL and returns it only if it is safe to use in an
 * <img src> attribute. Returns null for any value that does not pass.
 *
 * Allowed URL shapes:
 *  - blob: URLs (client-side file previews, always same-origin)
 *  - Same-origin absolute paths starting with /uploads/
 *  - S3 URLs matching https://<bucket>.s3.<region>.amazonaws.com/uploads/...
 *
 * Rejects javascript:, data:, vbscript:, and any other scheme.
 */
export function sanitizeIconUrl(
    raw: string | null | undefined,
    origin?: string
): string | null {
    if (!raw) return null;

    // Allow blob: URLs (generated by URL.createObjectURL, always same-origin)
    if (raw.startsWith('blob:')) {
        return raw;
    }

    // Block dangerous URI schemes explicitly before parsing.
    // This catches javascript:, data:, vbscript:, etc.
    const lower = raw.toLowerCase().trim();
    if (
        lower.startsWith('javascript:') ||
        lower.startsWith('data:') ||
        lower.startsWith('vbscript:')
    ) {
        return null;
    }

    try {
        // Determine origin — on the server this must be passed explicitly;
        // on the client we can read window.location.origin.
        const base =
            origin ??
            (typeof window !== 'undefined' ? window.location.origin : undefined);

        if (!base) return null;

        const url = new URL(raw, base);

        // Only allow http/https schemes (rejects javascript:, data:, etc.
        // even if the lower-case check above was bypassed via encoding)
        if (url.protocol !== 'http:' && url.protocol !== 'https:') {
            return null;
        }

        // Same-origin local uploads
        if (url.origin === new URL(base).origin) {
            if (!url.pathname.startsWith('/uploads/')) return null;
            return url.pathname; // return only the path, not a full URL
        }

        // S3 URLs: must be amazonaws.com and path must start with /uploads/
        if (
            url.hostname.endsWith('.amazonaws.com') &&
            url.protocol === 'https:' &&
            url.pathname.startsWith('/uploads/')
        ) {
            return url.toString();
        }

        return null;
    } catch {
        return null;
    }
}
