/**
 * Validates an icon URL and returns it only if it is safe to use in an
 * <img src> attribute. Returns null for any value that does not pass.
 *
 * Allowed URL shapes:
 *  - blob: URLs (client-side file previews, always same-origin)
 *  - Same-origin absolute paths starting with /uploads/
 *  - S3 URLs matching https://<bucket>.s3.<region>.amazonaws.com/uploads/...
 *
 * Rejects javascript:, data:, vbscript:, and any other scheme.
 */
export function sanitizeIconUrl(
    raw: string | null | undefined,
    origin?: string,
    allowedS3Hostname?: string | null
): string | null {
    if (!raw) return null;

    // Allow blob: URLs (generated by URL.createObjectURL, always same-origin)
    if (raw.startsWith('blob:')) {
        return raw;
    }

    // Block dangerous URI schemes explicitly before parsing.
    // This catches javascript:, data:, vbscript:, etc.
    const lower = raw.toLowerCase().trim();
    if (
        lower.startsWith('javascript:') ||
        lower.startsWith('data:') ||
        lower.startsWith('vbscript:')
    ) {
        return null;
    }

    try {
        // Determine origin — on the server this must be passed explicitly;
        // on the client we can read window.location.origin.
        const base =
            origin ??
            (typeof window !== 'undefined' ? window.location.origin : undefined);

        if (!base) return null;

        const url = new URL(raw, base);

        // Only allow http/https schemes (rejects javascript:, data:, etc.
        // even if the lower-case check above was bypassed via encoding)
        if (url.protocol !== 'http:' && url.protocol !== 'https:') {
            return null;
        }

        // Same-origin local uploads
        if (url.origin === new URL(base).origin) {
            if (!url.pathname.startsWith('/uploads/')) return null;
            return url.toString(); // return absolute URL for consistency across SSR/CSR
        }

        // S3 URLs: must match the EXACT configured hostname (if provided) and path must start with /uploads/
        if (
            url.hostname.endsWith('.amazonaws.com') &&
            url.protocol === 'https:' &&
            url.pathname.startsWith('/uploads/')
        ) {
            // Security: only allow the explicitly configured S3 hostname
            if (!allowedS3Hostname || url.hostname !== allowedS3Hostname) {
                return null;
            }
            // Convert to same-origin proxied URL so the server can fetch private
            // S3 objects and stream them to the client.
            if (base) return new URL(url.pathname, base).toString();
            return url.pathname;
        }

        // Azure Blob Storage URLs
        // Production: https://*.blob.core.windows.net/<container>/uploads/...
        // Azurite (Local): http://127.0.0.1:10000/.../uploads/...
        if (
            (url.hostname.endsWith('.blob.core.windows.net') || url.hostname === '127.0.0.1' || url.hostname === 'localhost') &&
            (url.protocol === 'https:' || url.protocol === 'http:') &&
            url.pathname.includes('/uploads/')
        ) {
            const idx = url.pathname.indexOf('/uploads/');
            if (idx !== -1) {
                if (base) return new URL(url.pathname.substring(idx), base).toString();
                return url.pathname.substring(idx); // Convert to proxy route
            }
            if (base) return new URL(url.pathname, base).toString();
            return url.pathname;
        }

        return null;
    } catch {
        return null;
    }
}
